version: '3'

services:
    db:
        image: mysql
        restart: always
        container_name: symfony-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
    php:
        build: php-fpm
        restart: always
        container_name: symfony-php
        volumes:
            - ${APP_PATH}:/opt/project
        ports:
            - 9000:9000

    nginx:
        build: nginx
        restart: always
        container_name: symfony-nginx
        volumes:
          - ${APP_PATH}:/opt/project
          - ./logs/nginx/:/var/log/nginx
          - ./nginx/etc/conf/symfony.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 8080:80

volumes:
  mysql-data:

networks:
  default:
    driver: bridge
