<?php

namespace AppBundle\Repository;

/**
 * RespondentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespondentRepository extends \Doctrine\ORM\EntityRepository
{
}
