<?php

namespace AppBundle\Repository;

/**
 * RespondentAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespondentAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
